export const companyTypes = [
  'Advertising',
  'Artist',
  'Artist Manager',
  'CMO (Collective Management Organisation)',
  'Composer',
  'Corporate',
  'Distributor',
  'DSP',
  'Film/TV',
  'Label',
  'Monitor',
  'Music Management Services',
  'PRO (Public Rights Organisation)',
  'Production Library',
  'Publisher',
  'Rights Holder',
  'Song Writer',
  'Sub Publisher',
];
